FROM golang:1.19
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .
RUN go build -o main ./cmd/main.go
EXPOSE 8080
RUN apt-get update && apt-get install -y rabbitmq-server
CMD service rabbitmq-server start && ./main